@SubscriberApi_HostAddress = https://localhost:7030
@loanId = 3730107a-9dac-48e4-b28f-5a22568438dc

GET {{SubscriberApi_HostAddress}}/weatherforecast/
Accept: application/json

###


GET {{SubscriberApi_HostAddress}}/api/Loans/
Accept: application/json

###
GET {{SubscriberApi_HostAddress}}/api/Loans/{{loanId}}
Accept: application/json


###
POST {{SubscriberApi_HostAddress}}/api/Loans/
Content-Type: application/json
Accept: application/json

{
  "borrowerName": "John Doe",
  "amount": 15000
}

###
PUT {{SubscriberApi_HostAddress}}/api/Loans/{{loanId}}
Content-Type: application/json

{
  "borrowerName": "Updated Name",
  "amount": 20000
}


###
DELETE {{SubscriberApi_HostAddress}}/api/Loans/{{loanId}}